Add gradle setup and caching
This update will pull the distribution bundle from the wrapper properties file and use it as the cache key. If there's not a cached dist already, it'll pull it down and then cache it.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -39,8 +39,30 @@ runs:
         java-version: '21'
         distribution: 'temurin'
 
-    - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1
+    - name: Get the current gradle distribution
+      id: get-gradle-dist
+      shell: bash
+      run: |
+        GRADLE_DIST=$(sed -E -n 's/distributionUrl=.*\/(gradle-.*.zip)/\1/p' ./ktserver/gradle/wrapper/gradle-wrapper.properties)
+        if [[ -z "$GRADLE_DIST" ]]; then
+          echo "Failed to locate the current gradle distribution"
+          exit 1
+        fi
+        echo "Found gradle distribution: $GRADLE_DIST"
+        echo gradle-dist="$GRADLE_DIST" >> "$GITHUB_OUTPUT"
+
+    - name: Gradle cache
+      uses: actions/cache@v4
+      id: gradle-cache
+      with:
+        path: ~/.gradle/wrapper/dists/
+        key: ${{ runner.os }}-${{ steps.get-gradle-dist.outputs.gradle-dist }}
+
+    - name: Download Gradle distribution
+      if: steps.gradle-cache.outputs.cache-hit != 'true'
+      run: ./gradlew tasks
+      working-directory: ./ktserver/
+      shell: bash
 
     - name: Cache Playwright binaries
       if: inputs.cache_playwright != '0'
@@ -48,7 +70,7 @@ runs:
       id: playwright-cache
       with:
         path: ~/.cache/ms-playwright
-        key: ${{ runner.os }}-playwright-${{ inputs.playwright_version  }}
+        key: ${{ runner.os }}-playwright-${{ inputs.playwright_version }}
 
     - name: Download Playwright dependencies and browsers
       if: inputs.cache_playwright != '0' && steps.playwright-cache.outputs.cache-hit != 'true'
